Add Debug info
liam4/slw pull request #23
Opened 2016-11-05 16:07 UTC by dekrain

...Thanks to (maybe) large files for hour delay

2016-11-05 16:15 UTC, bates64 requested changes
- Move the text, it'll overlap.
- Make sure you test your code.

2016-11-05 16:15 UTC, nanalan commented on src/SLW.js
> +      ctx.drawImage(Text.write('y: '+this.player.y), 2, 4)
These are gonna appear right next to eachother BTW.
The positions are absolute.

_Also it looks like you aren't testing your code locally before pushing?_

2016-11-05 16:16 UTC, bates64 approved these changes

2016-11-05 16:46 UTC, dekrain commented
I cannot test this because of error:
```
Tile.js:53:Uncaught RangeError: Tile W not found.
```

2016-11-05 16:55 UTC, dekrain commented
Hmm... I tried to change CRLF to LF, but without effects...

2016-11-06 09:23 UTC, nanalan commented
> Tile.js:53:Uncaught RangeError: Tile W not found.

That means that there's a Tile in your level `W` that isn't defined.

2016-11-06 09:44 UTC, dekrain commented
It's probably because `index.js` is encoded in CRLF format, but it should be LF

2016-11-06 11:57 UTC, nanalan commented
That'll make no difference, we're using a build system that removes most (if not all) line breaks / carriage returns anyway.

> That means that there's a Tile in your level W that isn't defined. Check src/levels.toml.

There's a `W` in your tilemap somewhere that's confusing it at runtime **not compile-time**.

2016-11-06 12:08 UTC, closed without merging

2016-11-06 17:57 UTC, dekrain commented
Yes, it's because gulp changed `~~~~\n~~~~` to `~~~~\r\n~~~~`

2016-11-06 18:27 UTC, liam4 commented
I'm not honestly sure where a string of `~` would appear anyways.

The original problem is "I can't run the game". Just to clarify - can you build and run the game now?

2016-11-06 18:31 UTC, dekrain commented
For example, in my src/levels.toml#L10
```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[CR][LF]
```
gulp changes it to
```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n
```
but expected is
```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n
```

2016-11-06 18:44 UTC, liam4 commented
Oh.. I guess that could be an issue with `toml` itself... hmm..

2016-11-06 19:23 UTC, nanalan commented
Interesting. Out of interest, do you use Windows, @dekrain? I believe the rest of us use Linux/Mac so that's probably why you're getting a linefeed result.

2016-11-06 19:25 UTC, nanalan commented
51b79807750fa0f009b9088769045c7e9f50fdc2 should fix your bug @dekrain - merge from master and build again to see if it fixes it.

2016-11-06 19:50 UTC, dekrain commented
Yes, I'm using Windows. Thanks for that commit.